# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_GPbP6VABe15KGSA67PPAOIFK18lmx7Z
"""

!pip install earthengine-api geemap

import ee
ee.Authenticate()
ee.Initialize()

!pip install earthengine-api geemap

import ee
ee.Authenticate(force=True)

ee.Initialize()

import ee
ee.Authenticate(auth_mode='notebook')

import ee
ee.Initialize()

!pip install earthengine-api geemap

import ee
ee.Authenticate(force=True)

import ee
ee.Initialize(project='earthengine-legacy')

import ee
ee.Initialize(opt_url='https://earthengine.googleapis.com')

import ee
ee.Initialize()

import ee
ee.Initialize(project='earthengine-legacy')

!pip install earthengine-api geemap

import ee
ee.Authenticate(force=True)

ee.Initialize(project='earth-engine-project-492507')

import geemap
Map = geemap.Map()
Map

import ee
import geemap

Map = geemap.Map()

image = ee.ImageCollection('LANDSAT/LC08/C02/T1_L2') \
    .filterDate('2022-01-01', '2022-12-31') \
    .median()

Map.addLayer(
    image,
    {
        'bands': ['SR_B4', 'SR_B3', 'SR_B2'],
        'min': 0,
        'max': 30000
    },
    'Satellite Image'
)

Map

chennai = ee.Geometry.Point([80.2707, 13.0827])

Map.centerObject(chennai, 10)

!pip install nbformat

import nbformat

nb = nbformat.read("your_notebook.ipynb", as_version=4)

if "widgets" in nb["metadata"]:
    del nb["metadata"]["widgets"]

nbformat.write(nb, "clean_notebook.ipynb")

# OLD IMAGE (2015)
old = ee.ImageCollection('LANDSAT/LC08/C02/T1_L2') \
    .filterDate('2015-01-01', '2015-12-31') \
    .median()

# NEW IMAGE (2023)
new = ee.ImageCollection('LANDSAT/LC08/C02/T1_L2') \
    .filterDate('2023-01-01', '2023-12-31') \
    .median()

old_ndvi = old.normalizedDifference(['SR_B5', 'SR_B4'])
new_ndvi = new.normalizedDifference(['SR_B5', 'SR_B4'])

Map.addLayer(old_ndvi, {'min': -1, 'max': 1, 'palette': ['white', 'green']}, 'NDVI 2015')
Map.addLayer(new_ndvi, {'min': -1, 'max': 1, 'palette': ['white', 'green']}, 'NDVI 2023')
Map

change = new_ndvi.subtract(old_ndvi)

Map.addLayer(change, {
    'min': -0.5,
    'max': 0.5,
    'palette': ['red', 'white', 'green']
}, 'Vegetation Change')

Map